# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac08c34b12d7cdfbf938a58f4bd8c2fdfd3b2baabae9c7cd94223a5d7f763ba44eded610d1a7cf5e208a0ea6812a66edbefeafa3896d671b3062aeefa127ad71

test:
  secret_key_base: e0bd56868cbbe24e8dd95ae98ce41fd4f036ccd7c100869dc0ecc3c0ed8d0a9058027f7d3a9282bdbe388fb386bf826f5888b941aaf071475c9fb041852b7921

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
